Create Endpoints for Login with Passport
sandboxnu/huskyhabits-backend pull request #10
Opened 2022-03-27 19:47 UTC by jciolfi

Will add comments & clean up code later

2022-03-29 06:32 UTC, nicoledanuwidjaja approved these changes
Only took a look at the passport related stuff, and the logic looks sound to me! Just a comment for project structuring

2022-03-29 06:32 UTC, nicoledanuwidjaja commented on repositories/user.ts
> +export const get_or_create_user = async (
Smh snake case

2022-03-29 06:32 UTC, nicoledanuwidjaja commented on passport.ts
> +  // Auth Routes
It would be nice to have this in `/routes` under an authentication route file, such as `auth.ts`.

2022-03-30 00:32 UTC, maxpinheiro requested changes
looks good, one small thing - I tried to start the server without filling out the .env and received a somewhat confusing error message:
`[ERROR] 20:27:28 TypeError: OAuth2Strategy requires a clientID option`
if you can make this error message more clear, you're good to go

2022-03-30 00:47 UTC, maxpinheiro approved these changes
lgtm 👍

2022-03-30 03:11 UTC, merged