create API for profiles
sandboxnu/huskyhabits-backend pull request #6
Opened 2022-02-27 20:58 UTC by Ross3102

Creates an API for getting the currently logged-in user's profile (for now just a dummy value), a specific profile by ID, and creating a new profile.

Closes #5

2022-02-27 21:15 UTC, connorlbark requested changes
thoughts:
- separate typescript model
- jest mockups to make sure the end points work as expected

2022-02-27 23:07 UTC, connorlbark commented
re discussion: separate profile photo endpoint? didn't specify that in the original ticket, but might make sense to add.

2022-03-19 07:27 UTC, nicoledanuwidjaja reviewed
Comments!

2022-03-19 07:27 UTC, nicoledanuwidjaja commented on routes/profiles.route.ts
> +  ProfileModel.findOne({ _id: id })
For future ref: database logic should be handled in the profile controller in `/controllers`.
Note for discussion: How do we want to have a separate API model specifically called for different endpoints?

2022-03-19 07:27 UTC, nicoledanuwidjaja commented on routes/profiles.route.ts
> +  ProfileModel.findOne({ _id: id })
Also noting that we want to add [OpenAPI](https://swagger.io/specification/) docs in the future

2022-03-23 05:39 UTC, closed without merging